version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    working_directory: ~/repo
    steps:
      - checkout 
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "setup.py" }}
      - run:
          command: |
            python3 -m virtualenv venv
            . venv/bin/activate
            pip install . coveralls
      - save_cache: # special step to save dependency cache
          key: deps1-{{ .Branch }}-{{ checksum "setup.py" }}
          paths:
            - "venv"
      - run:
          command: |
            . venv/bin/activate
            make check-all
            echo $COVERALLS_YML > .coveralls.yml
            coveralls
      - run:
          command: |
            . venv/bin/activate
            python setup.py sdist bdist_wheel
      - store_artifacts:
          path: dist/
          destination: dist
